site_name: Shuo Chen's Notes
site_url: https://chenshuo.com/notes
repo_url: https://github.com/chenshuo/notes
edit_uri: ''
site_author: Shuo Chen
theme:
  name: readthedocs
  analytics:
    gtag: G-4PL3B2ZGE8
extra_css: [extra.css]
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_HTML
markdown_extensions:
  - mdx_math
plugins:
  - mkdocs-jupyter:
      no_input: True
      remove_tag_config:
        remove_input_tags:
          - hide_code
        remove_cell_tags:
          - hide_cell
nav:
  - Home: index.md
  - Bugs: bugs.md
  - Kernel:
    - 'Study': kernel/study.md
    - 'Data Structures': kernel/data-structures.md
    - 'File Descriptor Table': kernel/file-descriptor-table.md
    - 'Epoll': kernel/epoll.md
    - 'Call Graphs': kernel/callgraph.md
    - 'SO_REUSEPRT': kernel/reuseport.md
    - 'Profiles': kernel/profiles.md
    - 'Changes': kernel/changes.md
    - 'Docs': kernel/docs.md
  - Languages:
    - lcc: lcc.md
    - Lua: lua.md
    - Memory Model: mem.md
  - Miscs:
    - Git: git.md
    - SSL: ssl.md
    - Links: links.md
  - Elec:
    - DSP: dsp.md
    - Reed-Solomon: reed-solomon.md
    - Î¼A78L05: UA78L05.ipynb
    - LM7805: LM7805.ipynb
    - TL431 Analysis and Simulation: tl431.md
