site_name: Shuo Chen's Notes
# theme: readthedocs
pages:
  - Home: index.md
  - Bugs: bugs.md
  - Git: git.md
  - Kernel:
    - 'Data Structures': kernel/data-structures.md
    - 'File Descriptor Table': kernel/file-descriptor-table.md
    - 'Epoll': kernel/epoll.md
    - 'Call Graphs': kernel/callgraph.md
    - 'SO_REUSEPRT': kernel/reuseport.md
    - 'Changes': kernel/changes.md
  - lcc: lcc.md
  - Lua: lua.md
  - mem: mem.md
  - SSL: ssl.md
  - Links: links.md
