site_name: Shuo Chen's Notes
theme:
  name: readthedocs
  analytics:
    gtag: G-4PL3B2ZGE8
extra_css: [extra.css]
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_HTML
markdown_extensions:
  - mdx_math
nav:
  - Home: index.md
  - Bugs: bugs.md
  - Kernel:
    - 'Study': kernel/study.md
    - 'Data Structures': kernel/data-structures.md
    - 'File Descriptor Table': kernel/file-descriptor-table.md
    - 'Epoll': kernel/epoll.md
    - 'Call Graphs': kernel/callgraph.md
    - 'SO_REUSEPRT': kernel/reuseport.md
    - 'Profiles': kernel/profiles.md
    - 'Changes': kernel/changes.md
    - 'Links': kernel/links.md
  - Languages:
    - lcc: lcc.md
    - Lua: lua.md
  - Git: git.md
  - Memory Model: mem.md
  - SSL: ssl.md
  - DSP: dsp.md
  - Links: links.md
